# https://taskfile.dev

version: "3"
output: prefixed
silent: false
dotenv: ['.env']

env:

vars:

tasks:
  default:
    cmds:
      - echo "tf devops"

  tf-doc:
    desc: terraform-docs - A utility to generate documentation from Terraform modules in various output formats
    dir: .
    cmds:
      - terraform-docs markdown . --output-file README.md

  tf-test:
    desc: terraform ops
    dir: examples/basic
    cmds:
      - terraform init
      - terraform fmt
      - terraform validate
      - tflint .
      - terraform plan